### PR TITLE
upgrade pekko versions

### PR DESCRIPTION
**Pull request by pjfanning**

### CODE REVIEW

**Review by raboof — COMMENTED** [review]
is there any way we can avoid having that gradle jar in there?

**Comment by pjfanning** [comment]
> is there any way we can avoid having that gradle jar in there?

unfortunately gradle users like gradle wrapper and it needs that jar

Can we log this as a separate issue?

**Comment by pjfanning** [comment]
> > is there any way we can avoid having that gradle jar in there?
> 
> unfortunately gradle users like gradle wrapper and it needs that jar
> 
> Can we log this as a separate issue?

@raboof is it ok to treat the gradle item separately?

**Comment by raboof** [comment]
yeah I suppose so!

**Review by raboof — APPROVED** [review]

**Pull request merged**
